#!perl -w
# run this document through perl to check its syntax
use Pod::Checker;
podchecker(\*DATA);
__END__

=head1 NAME

MacPerl Readme

=head1 BETA NOTES

The included Shuck is now in testing with new features.  Do NOT load
perltoc, it will crash you.  Thomas Wegner is developing it; please
see L<http://sf.net/projects/shuck/> for more details and bug reports.

There are bugs in MacPerl.  Please see L<http://dev.macperl.org/> for
more information on MacPerl, including bug reports.


=head1 SYNOPSIS

Welcome to MacPerl, the application that implements perl,
the programming language and environment, on Mac OS (Classic).
If you are running perl under Mac OS X, you don't want to be here
(unless you are in the Classic environment under Mac OS X).

=head1 DESCRIPTION

Please read the READMEs that come with MacPerl, but ignore the
installation instructions presented in the main README; they do not
apply to the Mac OS port of perl.

=head2 System Requirements

MacPerl 5.6 requires System 7.5 or above, and 8MB RAM.
You will be much better off with 64MB RAM, System 8.1,
and a PowerPC Macintosh.

=head2 Installing

MacPerl is installed by running the installer, and then setting up
the Online Help as described below.

To install the MPW perl tool, additionally follow the instructions
in F<Install.MPW_Perl>.

=head2 Online Help

There are two portions to the MacPerl documentation.  The first
is this README, along with the rest of the READMEs, licenses, and
manuals in the MacPerl F<Documentation> directory.

The other is the considerable amount of POD-based online help
that comes with Perl.  For this help to work, make sure you have:

=over 4

=item *

F<MacPerl Help>, the F<pod> folder, and F<Shuck> in the same folder
as your MacPerl application.

=item *

A recent version of Internet Config, or the Internet control panel
shipped with recent versions of Mac OS.  Internet Config is available
in many places online, and at:

	ftp://ftp.stairways.com/other/internetconfig-202.sit

=item *

Set up Internet Config (or the Internet control panel) with a helper
for "http", set to your web browser of choice, and the a helper for
"pod", set to F<Shuck>, the POD reader distributed with MacPerl.

=back

=head2 Mailing list

There are several MacPerl mailing lists covering various aspects of
MacPerl.  See the Perl mailing lists site for more information.

	http://lists.perl.org/

=head2 Distribution

MacPerl can always be obtained from the following locations, among
others:

	http://dev.macperl.org/
	http://www.cpan.org/ports/mac/
	ftp://ftp.cpan.org/CPAN/ports/mac/

MacPerl is avaiable on all the CPAN sites.  Find the CPAN mirror near you:

	http://mirror.cpan.org/

MacPerl is distributed in several forms.  The source is available
in a single archive.  The compiled, prepared distribution of MacPerl
is available in two forms, a web-based installer that allows you to
choose which pieces to download as-needed, and a large installer with
everything in it.  The web-based installer is recommended, as it
only downloads the components you need.

   MacPerl-5.6.1b1_web.bin
   MacPerl-5.6.1b1_full.bin
   ^       ^    ^^ ^    ^
   MacPerl |    || |    MacBinary Suffix ("bin")
           |    || Distribution Component (web", "full")
           |    |Build Number ("1")
           |    Type ("d"evelopment, "a"lpha, "b"eta, "r"elease)
           Perl Version ("5.6.1")

The web and full installers give the following options
(and variations on the themes):

=over 4

=item Easy Install

This installs the application (for your platform), the
documentation, and the library.  This will be the option
for most users.

=item MPW Tool

This installs the MPW tool (for your platform), a command-line
version of perl for use with ToolServer and Macintosh Programmer's
Workshop.  When selected, the documentation and library will be
selected as well, by default.

=item Developer Kit

This installs the source and the SYM files for debugging.

=back

=head2 Building

The perl 5.6.1 source itself builds on Mac OS, with some additional
pieces.  Support for Mac OS is now in the perl core, and MacPerl is
kept in close sync with regular perl releases.

You will need compilers and libraries, all of them freely
available.  These are linked to from the development site at
http://dev.macperl.org/. Go to that site for all things having to
do with MacPerl development.

=head1 CONTACT

Please send your bug reports, patches, and feature requests for MacPerl
to the MacPerl development site at http://dev.macperl.org/.  Also head
over there for the latest source and links to other sites.

=head1 CREDITS

Perl was ported to Mac OS by Matthias Neeracher E<lt>neeracher@mac.comE<gt>.
The port is maintained by Chris Nandor E<lt>pudge@pobox.comE<gt>.

The installer for MacPerl was created using Installer VISE from MindVision
Software. For more information on Installer VISE, contact: 

	MindVision Software 
	5901 North 58th Street 
	Lincoln, NE 68507 

	Voice: (402) 323-6600
	Fax: (402) 323-6611
	E-mail: mindvision@mindvision.com 
	http://www.mindvision.com 

The MacPerl application uses Mercutio MDEF, Copyright 1992-1998
by Ramon M. Felciano.

=head1 DATE

Last modified 2002.01.07.
