#!perl -wl
use strict;
use Mac::Glue ':glue';

# do cool stuff
my $aw = new Mac::Glue 'AppleWorks';
my $text = $aw->prop(text_body => document => 1);

$aw->activate;
$aw->make(new => 'document', at => location('front'));
die $^E if $^E;

$aw->set($text,
    to => "the quick brown fox jumped over the perl lazy programmers.");
die $^E if $^E;
sleep(2);

$aw->move(
    $aw->obj(word => 8 => $text),
    to => location(after => $aw->obj(word => 9 => $text))
);
die $^E if $^E;

printf("word contains 'e', begins with 'p', does not end with 's': %s\n",
    $aw->get($aw->obj(
        words => whose(AND =>
            [it => contains => 'e'], [it => begins_with => 'p'],
            [NOT => [it => ends_with => 's']]
        ), $text)
    )
);

__END__
