#!perl -wl

use Mac::Glue;

$s = new Mac::Glue 'Sherlock';
$s->activate;

@results = $s->search_internet('AltaVista', For => 'Mac::Glue');
warn $^E if $^E;

print @results ? join("\n", sort @results) : "No matches found.";

$s->quit;

__END__
